#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Make a Fibonacci while loop where x printed < 4mil
# For loop for % 2 to get only even numbers
# Sum the array


def fib():
    x = 0
    y = 1
    c = 0
    arr1 = []
    arr2 = []

    while x < 4000000:
        #print(x)
        arr1.append(x)
        z = x + y
        x = y
        y = z
        c += 1

    for x in arr1:
        if x % 2 == 0:
            arr2.append(x)
    #print(arr2)

    ans = sum(arr2)
    print(ans)

fib()

#solved
#ans 4613732
